language: c
compiler: gcc

before_install:
- sudo apt-get update
- sudo apt-get install poppler-utils
- sudo apt-get -y install texlive-full        
- cd travis-ci && ./getData.sh && cd -
  
script: 
- cd travis-ci
- ./test.sh
